version: '2'
services:
  web:
    build: ./web
    restart: always
    ports:
      - "80:8080"
    links:
      - mysql:mysql
    env_file: common.env

  mysql:
    restart: "always"
    build:
      context: "./mysql_files"
    ports:
      - "3306:3306"

volumes:
  data: {}
